/// One customer
table Customer
	lineageTag: 746b8dfc-c7f9-4397-affd-12bd82cecbb5

	column id
		dataType: int64
		isHidden
		lineageTag: cff29d89-f986-4ec8-b593-134900118b7f
		summarizeBy: none
		sourceColumn: id

	column code
		dataType: string
		lineageTag: 8e590469-47bb-4c77-a81c-f56bd87d5546
		summarizeBy: none
		sourceColumn: code

	column name
		dataType: string
		lineageTag: 6edb5c6a-bcce-488d-af8d-0342ebffcfa8
		summarizeBy: none
		sourceColumn: name

	partition Customer = m
		mode: import
		source =
				let
				    Source = ReportingSource{[Schema="public", Item="customers"]}[Data],
				    Filtered = Source,
				    Selected = Table.SelectColumns(Filtered, {"id", "code", "name"}),
				    Typed = Table.TransformColumnTypes(Selected, {{"id", Int64.Type}, {"code", type text}, {"name", type text}}),
				    Result = Typed
				in
				    Result
